### ISSUE TITLE
sample.py doesnt seem to run with torch 0.4 

### ISSUE THREAD

**Issue by yucongo** [IBM/pytorch-seq2seq#136]
With torch 0.3, it ran ok.

With torch 0.4:
python3 examples/sample.py --train_path $TRAIN_PATH --dev_path $DEV_PATH
    loss = self.acc_loss.data[0]
    Traceback (most recent call last):
    File "examples/sample.py", line 129, in <module>
        resume=opt.resume)
    File "/root/dl/github/pytorch-seq2seq/seq2seq/trainer/supervised_trainer.py", line 186, in train
        teacher_forcing_ratio=teacher_forcing_ratio)
    File "/root/dl/github/pytorch-seq2seq/seq2seq/trainer/supervised_trainer.py", line 103, in _train_epoches
        loss = self._train_batch(input_variables, input_lengths.tolist(), target_variables, model, teacher_forcing_ratio)
    File "/root/dl/github/pytorch-seq2seq/seq2seq/trainer/supervised_trainer.py", line 66, in _train_batch
        return loss.get_loss()
    File "/root/dl/github/pytorch-seq2seq/seq2seq/loss/loss.py", line 146, in get_loss
        nll /= self.norm_term
    RuntimeError: Expected object of type torch.FloatTensor but found type torch.LongTensor for argument #3 'other'

**Comment by kylegao91** [comment]
It should be fixed in 0.1.6
