### ISSUE TITLE
Float Division by Zero

### ISSUE THREAD

**Issue by Deepblue129** [IBM/pytorch-seq2seq#2]
```
Traceback (most recent call last):
  File "examples/sample.py", line 88, in <module>
    t.train(seq2seq, dataset, num_epochs=4, dev_data=dev_set, resume=opt.resume)
  File "/root/pytorch-seq2seq/seq2seq/trainer/supervised_trainer.py", line 160, in train
    resume=resume, dev_data=dev_data, teacher_forcing_ratio=teacher_forcing_ratio)
  File "/root/pytorch-seq2seq/seq2seq/trainer/supervised_trainer.py", line 111, in _train_epoches
    loss = self._train_batch(input_variables, target_variables, model, teacher_forcing_ratio)
  File "/root/pytorch-seq2seq/seq2seq/trainer/supervised_trainer.py", line 74, in _train_batch
    return loss.get_loss()
  File "/root/pytorch-seq2seq/seq2seq/loss/loss.py", line 140, in get_loss
    nll = super(Perplexity, self).get_loss()
  File "/root/pytorch-seq2seq/seq2seq/loss/loss.py", line 109, in get_loss
    return self.acc_loss.data[0] / self.norm_term
ZeroDivisionError: float division by zero
```

**Comment by avinash2692** [comment]
@Deepblue129 : Could you post a sample of the data you are running this on and also the arguments you used for the run ?

**Comment by Deepblue129** [comment]
@avinash2692 Played around with this a bit more. Looks like this error comes up when there is a newline at the end of the training file!
