### ISSUE TITLE
new version bug report

### ISSUE THREAD

**Issue by DataTerminatorX** [IBM/pytorch-seq2seq#67]
Updated to the latest version 1.3.0, run `examples/sample.py` and a bug appeared.

Below is the selected part of the log. Seems that a tensor transformation should be added

```
2017-09-05 21:00:28,942 seq2seq.trainer.supervised_trainer INFO     Finished epoch 4: Train Perplexity: 5.5457, Dev Perplexity: 1.0269
Type in a source sequence:1 2 3
1 2 3
Traceback (most recent call last):
  File "/home/Projects/pytorch-seq2seq/examples/sample.py", line 134, in <module>
    print(predictor.predict(seq))
  File "/home/Projects/pytorch-seq2seq/seq2seq/evaluator/predictor.py", line 38, in predict
    softmax_list, _, other = self.model(src_id_seq, [len(src_seq)], decoder_kick)
  File "/home/Projects/pytorch-seq2seq/v-seq2seq-py2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/Projects/pytorch-seq2seq/seq2seq/models/seq2seq.py", line 48, in forward
    teacher_forcing_ratio=teacher_forcing_ratio)
  File "/home/Projects/pytorch-seq2seq/v-seq2seq-py2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/Projects/pytorch-seq2seq/seq2seq/models/DecoderRNN.py", line 167, in forward
    function=function)
  File "/home/Projects/pytorch-seq2seq/seq2seq/models/DecoderRNN.py", line 92, in forward_step
    embedded = self.embedding(input_var)
  File "/home/Projects/pytorch-seq2seq/v-seq2seq-py2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/Projects/pytorch-seq2seq/v-seq2seq-py2/lib/python2.7/site-packages/torch/nn/modules/sparse.py", line 94, in forward
    self.scale_grad_by_freq, self.sparse
  File "/home/Projects/pytorch-seq2seq/v-seq2seq-py2/lib/python2.7/site-packages/torch/nn/_functions/thnn/sparse.py", line 53, in forward
    output = torch.index_select(weight, 0, indices.view(-1))
TypeError: torch.index_select received an invalid combination of arguments - got (torch.cuda.FloatTensor, int, torch.LongTensor), but expected (torch.cuda.FloatTensor source, int dim, torch.cuda.LongTensor index)

```

**Comment by kylegao91** [comment]
@DataTerminatorX Yeah travisCI doesn't have CUDA so it's not thoroughly tested...  It's fixed in `bugfix#67` and will be merged soon.
